### PR TITLE
Default cache doesn't handle family id correctly

### LINKED ISSUE #49: default_storage_manager_test is flaky
**Where is the issue?**
Tests

**What version of Go are you using (`go version`)?**
Test default_storage_manager_test.TestReadRefreshToken failed on go 1.14, passed on build previously

See if test is flaky and needs refactor

Passing test: https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/45/checks?check_run_id=1254682076
Failing test: https://github.com/AzureAD/microsoft-authentication-library-for-go/runs/1255127547?check_suite_focus=true

### PR DESCRIPTION
**Pull request by keegan-caruso**
Fixes #49 

Problem was both in the tests and the implementation.

This brings behavior more in line with MSAL4J's implementation: https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/0b20b1430ab57cd1f331935b79aa8542c5be9c9c/src/main/java/com/microsoft/aad/msal4j/TokenCache.java#L543

Could use an ack from someone on an MSAL team on cache key behavior.

Might be worth revisiting some of this API

### CODE REVIEW

**Comment by jennyf19** [comment]
@bgavrilMS can you take a look?

File: src/internal/tokencache/default_storage_manager.go [hunk 1]
```diff
@@ -96,37 +96,38 @@ func (m *defaultStorageManager) ReadRefreshToken(
 	defer lock.RUnlock()
 	if familyID != "" {
```
Comment (bgavrilMS) [inline src/internal/tokencache/default_storage_manager.go:97]: Interesting way of handling FOCI. I think it works. 

In .NET the algorithm we went with is: 

Simple algo: 

1. Try to find an FRT (i.e. ignore clientID filter)
2. If found, try to redeem the FRT
3. If AAD returns a token, hurray! Client is part of the family and we got a token.
3.1. If however AAD returns error code "client_mismatch" ( I think you need to ask AAD to add MSAL.GO on a special list for this to be returned) or "invalid_grant", then you know the client ID making the request is not part of the family

4. Assuming that FRT was either not found or it could not be redeemed, try to find the normal RT (filter by clientID)

Comment (bgavrilMS) [reply src/internal/tokencache/default_storage_manager.go:97]: More complex algo involves remembering in the token cache which ClientIDs are part of the family. MSAL doesn't know this from the start, so assume a client is part of the family if you don't know otherwise.

File: src/internal/tokencache/default_storage_manager.go [hunk 2]
```diff
@@ -96,37 +96,38 @@ func (m *defaultStorageManager) ReadRefreshToken(
...
 		for _, rt := range m.refreshTokens {
-			if testClientIDRefreshToken(rt, homeAccountID, envAliases, clientID) {
+			if matchFamilyRefreshToken(rt, homeAccountID, envAliases) {
```
Comment (bgavrilMS) [inline src/internal/tokencache/default_storage_manager.go:99]: yes, fair enough, you should not filter by clientID when looking for an FRT.

**Comment by bgavrilMS** [comment]
I assume the logic to call `ReadRefreshToken(familyID="xxx")` is based on AppMetadata ?

**Comment by bgavrilMS** [comment]
By the way, we have 2 apps in the lab that are part of the family, could be useful for writing an integration test, see: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/353be255d40c36bea67e2f816c4fca5ed902471a/tests/Microsoft.Identity.Test.Common/TestConstants.cs#L166

and here are the .NET integration tests: 

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/353be255d40c36bea67e2f816c4fca5ed902471a/tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/FociTests.cs#L46

**Review by bgavrilMS — APPROVED** [review]
LGTM assuming end to end tests work (see comments for details)

**Comment by keegan-caruso** [comment]
> I assume the logic to call `ReadRefreshToken(familyID="xxx")` is based on AppMetadata ?

Yes, that is here: https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/src/internal/tokencache/default_cache_manager.go#L82

File: src/internal/tokencache/default_storage_manager_test.go [hunk 3]
```diff
@@ -311,74 +312,203 @@ func TestWriteIDToken(t *testing.T) {
...
+				familyID:      "",
+				clientID:      "cid2",
+			},
+			want: nil,
+		},
+	}
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			if got := tt.m.ReadRefreshToken(tt.args.homeAccountID, tt.args.envAliases, tt.args.familyID, tt.args.clientID); !reflect.DeepEqual(got, tt.want) {
+				t.Errorf("defaultStorageManager.ReadRefreshToken() = %v, want %v", render.AsCode(got), render.AsCode(tt.want))
```
Comment (keegan-caruso) [inline src/internal/tokencache/default_storage_manager_test.go:509]: bringing in render as a test dependency so we get meaningful test failures. with just using %v on a struct with a pointer, you only get the pointer value (an address)

File: src/internal/tokencache/default_storage_manager.go (hunk 1 above)
Comment (keegan-caruso) [reply src/internal/tokencache/default_storage_manager.go:97]: Is it worth writing an issue for?

Comment (bgavrilMS) [reply src/internal/tokencache/default_storage_manager.go:97]: Is there an issue? I see msal.go already does the app metadata trick. I was trying to give some context around FOCI, not suggesting there is a bug.

Comment (keegan-caruso) [reply src/internal/tokencache/default_storage_manager.go:97]: The implementation seems a little different, looks like this one doesn't handle client_mismatch / invalid_grant and I don't think failover from FRT to RT

Comment (bgavrilMS) [reply src/internal/tokencache/default_storage_manager.go:97]: That's probably fine. I do wonder what happens if an app which is part of the family is removed from the family? Will MSAL go into an infinite loop or will the user just have to re-login interactively ? (second variant is acceptable imo )

Comment (henrik-me) [reply src/internal/tokencache/default_storage_manager.go:97]: leaving the family is supported, as far as I recall

---
In reply to: [506577218](https://github.com/AzureAD/microsoft-authentication-library-for-go/pull/50#discussion_r506577218) [](ancestors = 506577218)

Comment (bgavrilMS) [reply src/internal/tokencache/default_storage_manager.go:97]: If you leave the family, then on refreshing the FRT you get "client_mismatch" or "invalid_grant" from EVO, which msal MUST interpret as a `UIRequiredException`.

After interactive login, the app metadata will reflect the new state of world, where the app is no longer in the family. 

Should be fairly easy to unit test.
