### PR TITLE
Fix silent auth scopes and refresh behavior

### LINKED ISSUE #322: [Bug] wrong scope when getting token silently
**Which version of MSAL Go are you using?**
v0.51

**Where is the issue?**
* Public client
    * [ ] Device code flow
    * [ ] Username/Password (ROPC grant)
    * [x] Authorization code flow 

**Is this a new or an existing app?**

**What version of Go are you using (`go version`)?**

<pre>
$ go version
</pre>
go version go1.17.5 darwin/arm64

**What operating system and processor architecture are you using (`go env`)?**

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
╰─ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/marvinkurock/Library/Caches/go-build"
GOENV="/Users/marvinkurock/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/marvinkurock/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/marvinkurock/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/marvinkurock/development/go/tmw-cli/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/01/3y5lb3fs17d6g4jkgmt9fm8c0000gn/T/go-build1713909736=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>
I am trying to build a CLI authenticating against a web api.
I created a public app with the scope "guid/scope_name".
When I do 
```go
pubApp.AcquireTokenInteractive(context.Background(), scopes)
```
I get a correct token with the specified scope.
I can test die token against jwt.ms and get the correct scope inside the token and the API works correctly.

Also I have implemented a perstistent cache for the token.
When I wait until the access:_token is expired and try to run the cli again, I try to get a new token with:
```go
if len(accounts) > 0 {
    account := accounts[0]
    fmt.Printf("%v\n", account)
    var scopes = []string{viper.GetString("scope")}
    fmt.Printf("%v\n", scopes)
    result, err := pubApp.AcquireTokenSilent(context.Background(), scopes, public.WithSilentAccount(account))
    if err != nil {
      fmt.Println(err)
      panic("Could not aquire token")
    }
```
It also works and I do get a new token without a browser prompt.
BUT the token has a scope of "User.Read", but I still requested the same scope as initially "guid/scope_name".
Is this a bug or am I doing something wrong?

Update:
I set a proxy and caught the request made to AAD. It requested only scopes „profile openid offline..“ but my scope was not given in die querystring. I did send the request manually with my guid/scope_name added and I got a token with my requested scope. 
so why is aquireTokenSilent ignoring my scope?
I printed it prior to the call and the scope variable is correct :/

### PR DESCRIPTION
**Pull request by chlowell**
This fixes two problems with silent authentication:
  1. it ignores the requested scopes (closes #322; thanks @mkurock)
  1. it uses refresh tokens only to refresh expired access tokens i.e., silent authentication for a given scope succeeds only when the cache contains an access token (expired or not) for that scope

Fixing the first problem is straightforward: just pass the right argument. The second problem is more complex. It arises in the cache's `Read` method, which assumes the caller requires an access token matching the given parameters and returns an error when it doesn't find one. If the caller could in principle use a previously cached refresh token to authenticate, it never gets the chance because `Read` doesn't return that refresh token. I fixed this by having `Read` continue past an access token cache miss to fetch more data, such as a refresh token, before returning. This means `Read` now returns a zero-valued access token in some cases. This is okay because `base.Client` is the only caller and already validates access tokens before returning them to the application.

### CODE REVIEW

File: apps/internal/base/base.go [hunk 1]
```diff
@@ -262,15 +262,15 @@ func (b Client) AcquireTokenSilent(ctx context.Context, silent AcquireTokenSilen
...
-			return AuthResult{}, errors.New("no refresh token found")
+			return AuthResult{}, errors.New("no token found")
 		}
 
 		var cc *accesstokens.Credential
 		if silent.RequestType == accesstokens.ATConfidential {
 			cc = silent.Credential
 		}
 
-		token, err := b.Token.Refresh(ctx, silent.RequestType, b.AuthParams, cc, storageTokenResponse.RefreshToken)
```
Comment (chlowell) [inline apps/internal/base/base.go:273]: This is problem 1. `b.AuthParams` holds common parameters for all auth requests. Its type has a scopes field but on this instance that field always has a zero value (default scopes are handled elsewhere). `authParams` is an instance of the same type which carries overriding values for this auth request, and the scopes requested by the user application.

File: apps/internal/base/internal/storage/storage.go [hunk 2]
```diff
@@ -94,10 +94,7 @@ func (m *Manager) Read(ctx context.Context, authParameters authority.AuthParams,
 		return TokenResponse{}, err
 	}
 
-	accessToken, err := m.readAccessToken(homeAccountID, metadata.Aliases, realm, clientID, scopes)
```
Comment (chlowell) [inline apps/internal/base/internal/storage/storage.go:97]: This is problem 2. This helper returns an error when it misses. A miss isn't fatal and using an error to signal one requires the caller to inspect the error to determine whether it's safe to proceed. I could've used a sentinel error for misses but that seemed excessive because the helper really doesn't need to return an error--it only searches a map.

**Review by bgavrilMS — COMMENTED** [review]
LGTM, at least by reading the tests.

**Review by keegan-caruso — APPROVED** [review]

**Comment by chlowell** [comment]
Thanks for the additional context. I added a test to verify granted scopes are handled correctly in caching. Clients appear to add "openid profile offline_access" scopes as you describe--at least, I see this in live traffic and the code looks right--but that doesn't have unit test coverage today (#329).

File: apps/internal/base/internal/storage/items.go [hunk 3]
```diff
@@ -103,8 +103,14 @@ func (a AccessToken) Key() string {
 	)
 }
 
+// FakeValidate enables tests to fake access token validation
+var FakeValidate func(AccessToken) error
+
 // Validate validates that this AccessToken can be used.
 func (a AccessToken) Validate() error {
+	if FakeValidate != nil {
```
Comment (ivarprudnikov) [inline apps/internal/base/internal/storage/items.go:111]: It looks like a bad idea. It should be possible to just pass a valid token in the test.

Comment (chlowell) [reply apps/internal/base/internal/storage/items.go:111]: To give some context, the cache calls this method before writing a token and won't write that token if this method returns an error. This method will return an error if the token expires within the next 5 minutes. A test that requires the cache to contain an expired token therefore can't pass in a valid token unless it then waits for that token to expire. Perhaps the cache shouldn't check expiry before writing tokens (too big a change to contemplate here) but there are of course other ways to work around this. The test could cache a token that expires in 5 minutes and 1 millisecond then `time.Sleep(2*time.Millisecond)`. I like that approach, but I still prefer `FakeValidate` because it may prove useful in other test cases and doesn't require the one I'm adding in this PR to take a dependency on timing or behavior not under test.

**Review by ivarprudnikov — APPROVED** [review]
